-- MySQL Script generated by MySQL Workbench
-- Wed Jul 17 00:12:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema legodb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `legodb` DEFAULT CHARACTER SET utf8 ;
USE `legodb` ;

-- -----------------------------------------------------
-- Table `legodb`.`inventory_sets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`inventory_sets` ;

CREATE TABLE IF NOT EXISTS `legodb`.`inventory_sets` (
  `inventory_id` INT NOT NULL,
  `set_num` VARCHAR(45) NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `fk_inventory_sets_2_idx` (`set_num` ASC) VISIBLE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `legodb`.`themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`themes` ;

CREATE TABLE IF NOT EXISTS `legodb`.`themes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `parent_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `legodb`.`sets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`sets` ;

CREATE TABLE IF NOT EXISTS `legodb`.`sets` (
  `set_num` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `year` YEAR(4) NULL,
  `theme_id` INT NULL,
  `num_parts` VARCHAR(45) NULL,
  PRIMARY KEY (`set_num`),
  INDEX `fk_sets_1_idx` (`theme_id` ASC) VISIBLE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `legodb`.`inventories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`inventories` ;

CREATE TABLE IF NOT EXISTS `legodb`.`inventories` (
  `id` INT NOT NULL,
  `version` INT NULL,
  `set_num` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventories_1_idx` (`set_num` ASC) VISIBLE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `legodb`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`colors` ;

CREATE TABLE IF NOT EXISTS `legodb`.`colors` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `rgb` VARCHAR(45) NULL,
  `is_trans` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `legodb`.`part_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`part_categories` ;

CREATE TABLE IF NOT EXISTS `legodb`.`part_categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `legodb`.`parts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`parts` ;

CREATE TABLE IF NOT EXISTS `legodb`.`parts` (
  `part_num` VARCHAR(45) NOT NULL COMMENT ' ',
  `name` VARCHAR(200) NULL,
  `part_cat_id` INT NULL,
  PRIMARY KEY (`part_num`),
  INDEX `fk_parts_1_idx` (`part_cat_id` ASC) VISIBLE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `legodb`.`inventory_parts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legodb`.`inventory_parts` ;

CREATE TABLE IF NOT EXISTS `legodb`.`inventory_parts` (
  `inventory_id` INT NULL,
  `part_num` VARCHAR(45) NULL,
  `color_id` INT NULL,
  `quantity` INT NULL,
  `is_spare` VARCHAR(45) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_inventory_parts_2_idx` (`color_id` ASC) VISIBLE,
  INDEX `fk_inventory_parts_3_idx` (`part_num` ASC) VISIBLE
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
